### ISSUE TITLE
Relation to other shell script checkers

### ISSUE THREAD

**Issue by swsnr** [Gnouc/flycheck-checkbashisms#2]
Before we can [add this repo to our list of extensions](https://github.com/flycheck/flycheck.github.io/pull/13) I would like to see the relation between this syntax checker and the built-in shell script checkers clarified.

Currently I see a couple of issues:
- `flycheck-checkbashisms-setup` adds the new syntax checker to the front of `flycheck-checkers`, overriding _all_ built-in syntax checkers.
- `sh-checkbashisms` does not have any `:next-checkers` at all.  Combined with the above this essentially means that it **disables all built-in** checkers for shells other than bash.
- `sh-checkbashisms` runs for Zsh scripts, where it's probably not desired.

In my opinion that's a no-go, and it means that we cannot recommend this extension to our users with good conscience.  Before we add this repo to our list of extensions, I'd like to see a couple of fixes applied.  Specifically:
- `sh-checkbashisms` should only run for `sh` scripts.
- It should be added at the _end_ of `flycheck-checkers`, to run after the built-in syntax checkers.
- It should register itself to run after the built-in sh syntax checkers with `flycheck-add-next-checker`.

In the end a sh buffer should be checked with `sh-posix-dash` or `sh-bash-posix`, then `sh-shellcheck` and ultimately `sh-checkbashisms`. `sh-checkbashishms` should not run for bash or zsh scripts, or any other non-sh shell script.

**Comment by cuonglm** [comment]
@lunaryorn Thanks for the deep review. Those issues also in my mind for the next version of `flycheck-checkbashisms`. (You can see how I used it as [the next checker after `sh-shellcheck`](https://github.com/Gnouc/emacs.d/blob/master/init.el#L189)).

I agree with all the issues but the one:
- sh-checkbashisms should only run for sh scripts.

Although the purpose of `checkbashisms` is `performs basic checks on /bin/sh shell scripts for the possible presence of bashisms`, it's clear that you can face `bashisms` in other shells, too.

The two example are [`printf -v`](http://www.zsh.org/mla/workers/2016/msg00006.html) and [`${!var}`](http://unix.stackexchange.com/a/251896/38906), which are not available in any shell other than `bash`.

**Comment by swsnr** [comment]
> Although the purpose of checkbashisms is performs basic checks on /bin/sh shell scripts for the possible presence of bashisms, it's clear that you can face bashisms in other shells, too.

Yes, but `checkbashism` will also detect "bashisms" which are perfectly valid syntax in Zsh, won't it?  As such, it'd be prone to false positives in Zsh scripts, wouldn't it?

**Comment by cuonglm** [comment]
@lunaryorn Ah, right, fair point!

The fix will come soon.

**Comment by swsnr** [comment]
@Gnouc Great, thank you :+1:  Please mention me on this issue if you have questions or need help.  When you're finished I'll review the extension again, and add it to our extension list if there are no further issues :relaxed:

**Comment by Gnouc** [comment]
@lunaryorn I attempt a fix in [this commit](https://github.com/Gnouc/flycheck-checkbashisms/commit/8fb678f0420bebb8913a0c729e8321e5da5dc4e1). Although `(add-to-list 'flycheck-checkers 'sh-checkbashisms t)` was used, `sh-checkbashisms` still present in the beginning of `'flycheck-checkers` list. Did I miss something?

**Comment by Gnouc** [comment]
@lunaryorn Ah, my bad, that's the cache from compiled file.

It should work now!

**Comment by swsnr** [comment]
@Gnouc Looks good, just two minor issues:
- Please also add your checker after `sh-posix-bash` which is used as fallback if `dash` is not installed.
- Why did you use `error` in `flycheck-add-next-checker`?  Do you want to apply `checkbashisms` even if the file contains a syntax error?

**Comment by cuonglm** [comment]
@lunaryorn [Fixed it](https://github.com/Gnouc/flycheck-checkbashisms/commit/9fc680d09bc54fc569513343e194e086d07644ff).

No, that's not what I want but I mis-understood the `flycheck-add-next-checker`. Reading its source again and got it now. Thanks for all the information :+1:

**Comment by swsnr** [comment]
@Gnouc Great, looks great, please just address [my comment](https://github.com/Gnouc/flycheck-checkbashisms/commit/9fc680d09bc54fc569513343e194e086d07644ff#commitcomment-15230705), 

> No, that's not what I want but I mis-understood the flycheck-add-next-checker. Reading its source again and got it now. Thanks for all the information :+1:

Yes, I'm sorry for this confusion.  This API is really hard to understand, and our system really flawed.  I used this discussion as an opportunity to [put a redesign of `:next-checkers` in our backlog](https://github.com/flycheck/flycheck/issues/836).  We really need to come up with a better system that's easier to understand.

**Comment by cuonglm** [comment]
It was [fixed](https://github.com/Gnouc/flycheck-checkbashisms/commit/0faf6379b2e70554956737294462b4425bc0372e).

:+1: Hope we have some interesting ideals from our community for redesigning.
