### ISSUE TITLE
suspicious state from checker when shebang uses 'env'

### ISSUE THREAD

**Issue by articuluxe** [Gnouc/flycheck-checkbashisms#3]
When I have a shell script that starts with:
# !/usr/bin/env sh

the flycheck checker returns:
"Suspicious state from syntax checker sh-checkbashisms: Checker sh-checkbashisms returned non-zero exit code 2, but  no errors from output: script (stdin) does not appear to be a /bin/sh script; skipping.  

Checker definition probably flawed."

**Comment by cuonglm** [comment]
`flycheck-checkbashisms` use [sh-shell](http://repo.or.cz/emacs.git/blob/HEAD:/lisp/progmodes/sh-script.el#l415) variable from `sh-mode` to verify `sh` or not.

Look at the code of [sh-set-shell](http://repo.or.cz/emacs.git/blob/HEAD:/lisp/progmodes/sh-script.el#l1675), it covered the `/usr/bin/env` in shebang. Maybe your shebang is not valid.

**Comment by cuonglm** [comment]
@danrharms Ah, that's not `sh-mode` error, but that's `checkbashisms` itself.

`checkbashisms` can not detect script with `env` in shebang.

**Comment by cuonglm** [comment]
Workaround in this [commit](https://github.com/Gnouc/flycheck-checkbashisms/commit/39362240b8e38e6ddc1da2e2c2229e3fecdf6057)

**Comment by articuluxe** [comment]
Thank you very much, that helps.
